# Generated by Django 6.1.1 on 2026-09-06 05:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Dehradun', max_length=100)),
                ('state', models.CharField(default='Uttarakhand', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('whatsapp', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('has_ambulance', models.BooleanField(default=True)),
                ('is_available_24_7', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('reporter_name', models.CharField(max_length=150)),
                ('reporter_phone', models.CharField(max_length=20)),
                ('reporter_email', models.EmailField(max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address_text', models.TextField(blank=True, help_text='Landmark or street description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('processed_image', models.ImageField(blank=True, null=True, upload_to='reports/processed/')),
                ('is_animal_detected', models.BooleanField(default=False)),
                ('detected_animal', models.CharField(default='Unknown', max_length=100)),
                ('detected_injuries', models.TextField(blank=True, default='None detected')),
                ('apparent_severity', models.CharField(choices=[('NORMAL', 'Minor / Normal (Non-Emergency)'), ('MODERATE', 'Moderate Injury'), ('CRITICAL', 'Critical / Severe (Immediate Rescue Needed)'), ('UNKNOWN', 'Unverified / Direct Report')], default='UNKNOWN', max_length=20)),
                ('ai_first_aid_guidance', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported / Triage Pending'), ('SEARCHING', 'Searching Nearby Shelters'), ('DISPATCHED', 'Rescue Team Dispatched / Ambulance En Route'), ('ADMITTED', 'Arrived at Hospital / Under Treatment'), ('RESOLVED', 'Rescued & Recovered'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=20)),
                ('ambulance_assigned', models.BooleanField(default=False)),
                ('ambulance_driver_name', models.CharField(blank=True, max_length=100)),
                ('ambulance_driver_phone', models.CharField(blank=True, max_length=20)),
                ('ambulance_lat', models.FloatField(blank=True, null=True)),
                ('ambulance_lng', models.FloatField(blank=True, null=True)),
                ('eta_minutes', models.IntegerField(default=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_hospital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_cases', to='rescue_app.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='HospitalStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='rescue_app.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
