# Generated by Django 6.1.1 on 2026-09-06 06:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambulance_number', models.CharField(max_length=50, unique=True)),
                ('driver_name', models.CharField(max_length=100)),
                ('driver_phone', models.CharField(max_length=20)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('BUSY', 'Busy'), ('MAINTENANCE', 'Maintenance'), ('OFFLINE', 'Offline')], default='AVAILABLE', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RescueCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
                ('city', models.CharField(default='Dehradun', max_length=100)),
                ('state', models.CharField(default='Uttarakhand', max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('capacity', models.PositiveIntegerField(default=10)),
                ('current_cases', models.PositiveIntegerField(default=0)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='ambulance_driver_name',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='ambulance_driver_phone',
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported / Triage Pending'), ('SEARCHING', 'Searching Nearby Rescue Centers'), ('DISPATCHED', 'Rescue Team Dispatched / Ambulance En Route'), ('ADMITTED', 'Arrived at Hospital / Under Treatment'), ('RESOLVED', 'Rescued & Recovered'), ('CANCELLED', 'Cancelled')], default='REPORTED', max_length=20),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='assigned_ambulance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports', to='rescue_app.ambulance'),
        ),
        migrations.AddField(
            model_name='ambulance',
            name='rescue_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ambulances', to='rescue_app.rescuecenter'),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='assigned_rescue_center',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emergency_reports', to='rescue_app.rescuecenter'),
        ),
    ]
