# Generated by Django 5.0.14 on 2026-08-15 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(default='City Center', max_length=100)),
                ('phone', models.CharField(max_length=25)),
                ('emergency_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('latitude', models.FloatField(help_text='Hospital GPS Latitude (e.g. 28.6139)')),
                ('longitude', models.FloatField(help_text='Hospital GPS Longitude (e.g. 77.2090)')),
                ('capacity', models.PositiveIntegerField(default=25, help_text='Total animal ward capacity')),
                ('current_occupancy', models.PositiveIntegerField(default=0)),
                ('has_24_7_ambulance', models.BooleanField(default=True)),
                ('has_icu', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ambulance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(max_length=50)),
                ('driver_name', models.CharField(max_length=120)),
                ('driver_phone', models.CharField(max_length=25)),
                ('paramedic_name', models.CharField(blank=True, max_length=120, null=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available at Base'), ('DISPATCHED', 'Dispatched / En Route'), ('ON_SCENE', 'On Scene / Rescuing'), ('RETURNING', 'Transporting to Clinic'), ('MAINTENANCE', 'Under Maintenance / Off Duty')], default='AVAILABLE', max_length=20)),
                ('current_latitude', models.FloatField(blank=True, null=True)),
                ('current_longitude', models.FloatField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambulances', to='hospitals.hospital')),
            ],
        ),
    ]
