# Generated by Django 5.0.14 on 2026-08-15 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RescueReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(editable=False, max_length=20, unique=True)),
                ('reporter_name', models.CharField(default='Anonymous Citizen', max_length=120)),
                ('reporter_phone', models.CharField(blank=True, max_length=25, null=True)),
                ('image', models.ImageField(upload_to='rescues/%Y/%m/')),
                ('annotated_image', models.CharField(blank=True, max_length=255, null=True)),
                ('species', models.CharField(choices=[('DOG', 'Dog / Puppy'), ('CAT', 'Cat / Kitten'), ('BIRD', 'Bird / Avian'), ('COW', 'Cow / Cattle'), ('HORSE', 'Horse / Donkey'), ('WILDLIFE', 'Wildlife / Exotic'), ('OTHER', 'Other Animal')], default='DOG', max_length=20)),
                ('species_detected_by_ai', models.CharField(blank=True, max_length=100, null=True)),
                ('injury_severity', models.CharField(choices=[('CRITICAL', 'Critical (Immediate Life Threat)'), ('SEVERE', 'Severe (Urgent Care Needed)'), ('MODERATE', 'Moderate (Stable / Fractures / Wounds)'), ('MINOR', 'Minor (Superficial / Checkup)')], default='MODERATE', max_length=20)),
                ('ai_confidence', models.FloatField(default=90.0)),
                ('ai_symptoms', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(help_text='GPS Latitude')),
                ('longitude', models.FloatField(help_text='GPS Longitude')),
                ('location_address', models.CharField(blank=True, max_length=255, null=True)),
                ('landmark_notes', models.TextField(blank=True, help_text='e.g. Near Blue Gate, behind supermarket', null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported & Analyzed by AI'), ('ASSIGNED', 'Hospital Assigned & Reviewing'), ('DISPATCHED', 'Ambulance Dispatched / En Route'), ('ON_SCENE', 'Rescue Team Arrived On Scene'), ('RESCUED', 'Animal Secured & In Transit'), ('IN_TREATMENT', 'Admitted to Hospital & Under Treatment'), ('RECOVERED', 'Recovered / Safe / Adoptable'), ('CLOSED', 'Case Resolved & Closed')], default='REPORTED', max_length=25)),
                ('first_aid_viewed', models.BooleanField(default=False)),
                ('medical_notes', models.TextField(blank=True, null=True)),
                ('recovery_photo', models.ImageField(blank=True, null=True, upload_to='recovery/%Y/%m/')),
                ('reported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ambulance_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='hospitals.ambulance')),
                ('hospital_assigned', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to='hospitals.hospital')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RescueStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
                ('message', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='rescue.rescuereport')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
